import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidebarMenu from "./SidebarMenu";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen  dark:bg-black">
          <SidebarMenu className="w-64 shadow-md" />
          <main className="flex-1 flex flex-col">
            <Header />
            <main className="flex-1 p-3">{children}</main>
          </main>
        </div>
      </body>
    </html>
  );
}
